/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { faker } from "@faker-js/faker";

import { HttpResponse, delay, http } from "msw";

import type { ApiResponseListAirportResponseDTO } from "../openAPIDefinition.schemas";

export const getAirportsResponseMock = (
  overrideResponse: Partial<ApiResponseListAirportResponseDTO> = {}
): ApiResponseListAirportResponseDTO => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  code: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  message: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  data: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1
    ).map(() => ({
      id: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      code: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      name: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      city: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      country: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
    })),
    undefined,
  ]),
  ...overrideResponse,
});

export const getAirportsMockHandler = (
  overrideResponse?:
    | ApiResponseListAirportResponseDTO
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0]
      ) =>
        | Promise<ApiResponseListAirportResponseDTO>
        | ApiResponseListAirportResponseDTO)
) => {
  return http.get("*/api/airports", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getAirportsResponseMock()
      ),
      { status: 200, headers: { "Content-Type": "application/json" } }
    );
  });
};
export const getAirportControllerMock = () => [getAirportsMockHandler()];
