/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { faker } from "@faker-js/faker";

import { HttpResponse, delay, http } from "msw";

import type {
  ApiResponseFlightResponseDTO,
  ApiResponsePagedResponseDTOFlightResponseDTO,
} from "../openAPIDefinition.schemas";

export const getSearchFlightsResponseMock = (
  overrideResponse: Partial<ApiResponsePagedResponseDTOFlightResponseDTO> = {}
): ApiResponsePagedResponseDTOFlightResponseDTO => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  code: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  message: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  data: faker.helpers.arrayElement([
    {
      content: faker.helpers.arrayElement([
        Array.from(
          { length: faker.number.int({ min: 1, max: 10 }) },
          (_, i) => i + 1
        ).map(() => ({
          id: faker.helpers.arrayElement([
            faker.number.int({ min: undefined, max: undefined }),
            undefined,
          ]),
          flightNumber: faker.helpers.arrayElement([
            faker.string.alpha(20),
            undefined,
          ]),
          departure: faker.helpers.arrayElement([
            faker.string.alpha(20),
            undefined,
          ]),
          destination: faker.helpers.arrayElement([
            faker.string.alpha(20),
            undefined,
          ]),
          departureDate: faker.helpers.arrayElement([
            faker.string.alpha(20),
            undefined,
          ]),
          departureTime: faker.helpers.arrayElement([
            faker.string.alpha(20),
            undefined,
          ]),
          price: faker.helpers.arrayElement([
            faker.number.int({ min: undefined, max: undefined }),
            undefined,
          ]),
        })),
        undefined,
      ]),
      pageNumber: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      pageSize: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      totalElements: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      totalPages: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      first: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
      last: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
    },
    undefined,
  ]),
  ...overrideResponse,
});

export const getFlightDetailResponseMock = (
  overrideResponse: Partial<ApiResponseFlightResponseDTO> = {}
): ApiResponseFlightResponseDTO => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  code: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  message: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  data: faker.helpers.arrayElement([
    {
      id: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      flightNumber: faker.helpers.arrayElement([
        faker.string.alpha(20),
        undefined,
      ]),
      departure: faker.helpers.arrayElement([
        faker.string.alpha(20),
        undefined,
      ]),
      destination: faker.helpers.arrayElement([
        faker.string.alpha(20),
        undefined,
      ]),
      departureDate: faker.helpers.arrayElement([
        faker.string.alpha(20),
        undefined,
      ]),
      departureTime: faker.helpers.arrayElement([
        faker.string.alpha(20),
        undefined,
      ]),
      price: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
    },
    undefined,
  ]),
  ...overrideResponse,
});

export const getSearchFlightsMockHandler = (
  overrideResponse?:
    | ApiResponsePagedResponseDTOFlightResponseDTO
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0]
      ) =>
        | Promise<ApiResponsePagedResponseDTOFlightResponseDTO>
        | ApiResponsePagedResponseDTOFlightResponseDTO)
) => {
  return http.get("*/api/flights", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getSearchFlightsResponseMock()
      ),
      { status: 200, headers: { "Content-Type": "application/json" } }
    );
  });
};

export const getFlightDetailMockHandler = (
  overrideResponse?:
    | ApiResponseFlightResponseDTO
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0]
      ) => Promise<ApiResponseFlightResponseDTO> | ApiResponseFlightResponseDTO)
) => {
  return http.get("*/api/flights/:id", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getFlightDetailResponseMock()
      ),
      { status: 200, headers: { "Content-Type": "application/json" } }
    );
  });
};
export const getFlightControllerMock = () => [
  getSearchFlightsMockHandler(),
  getFlightDetailMockHandler(),
];
