/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  // ApiResponseFlightResponseDTO,
  // ApiResponsePagedResponseDTOFlightResponseDTO,
  FlightResponseDTO,
  PagedResponseDTOFlightResponseDTO,
  SearchFlightsParams,
} from "../openAPIDefinition.schemas";

import { axiosInstance } from ".././axiosInstance";

export const searchFlights = (
  params: SearchFlightsParams,
  signal?: AbortSignal
) => {
  return axiosInstance<PagedResponseDTOFlightResponseDTO>({
    url: `/api/flights`,
    method: "GET",
    params,
    signal,
  });
};

export const getSearchFlightsQueryKey = (params: SearchFlightsParams) => {
  return [`/api/flights`, ...(params ? [params] : [])] as const;
};

export const getSearchFlightsQueryOptions = <
  TData = Awaited<ReturnType<typeof searchFlights>>,
  TError = unknown
>(
  params: SearchFlightsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchFlights>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSearchFlightsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof searchFlights>>> = ({
    signal,
  }) => searchFlights(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchFlights>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SearchFlightsQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchFlights>>
>;
export type SearchFlightsQueryError = unknown;

export function useSearchFlights<
  TData = Awaited<ReturnType<typeof searchFlights>>,
  TError = unknown
>(
  params: SearchFlightsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchFlights>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchFlights>>,
          TError,
          Awaited<ReturnType<typeof searchFlights>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchFlights<
  TData = Awaited<ReturnType<typeof searchFlights>>,
  TError = unknown
>(
  params: SearchFlightsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchFlights>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchFlights>>,
          TError,
          Awaited<ReturnType<typeof searchFlights>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchFlights<
  TData = Awaited<ReturnType<typeof searchFlights>>,
  TError = unknown
>(
  params: SearchFlightsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchFlights>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useSearchFlights<
  TData = Awaited<ReturnType<typeof searchFlights>>,
  TError = unknown
>(
  params: SearchFlightsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchFlights>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSearchFlightsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getFlightDetail = (id: number, signal?: AbortSignal) => {
  return axiosInstance<FlightResponseDTO>({
    url: `/api/flights/${id}`,
    method: "GET",
    signal,
  });
};

export const getFlightDetailQueryKey = (id: number) => {
  return [`/api/flights/${id}`] as const;
};

export const getFlightDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof getFlightDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFlightDetail>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFlightDetailQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getFlightDetail>>> = ({
    signal,
  }) => getFlightDetail(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getFlightDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFlightDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFlightDetail>>
>;
export type GetFlightDetailQueryError = unknown;

export function useGetFlightDetail<
  TData = Awaited<ReturnType<typeof getFlightDetail>>,
  TError = unknown
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFlightDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFlightDetail>>,
          TError,
          Awaited<ReturnType<typeof getFlightDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFlightDetail<
  TData = Awaited<ReturnType<typeof getFlightDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFlightDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFlightDetail>>,
          TError,
          Awaited<ReturnType<typeof getFlightDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFlightDetail<
  TData = Awaited<ReturnType<typeof getFlightDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFlightDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetFlightDetail<
  TData = Awaited<ReturnType<typeof getFlightDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFlightDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFlightDetailQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
