/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { faker } from "@faker-js/faker";

import { HttpResponse, delay, http } from "msw";

import type {
  ApiResponseBookingResponseDTO,
  ApiResponsePagedResponseDTOBookingResponseDTO,
} from "../openAPIDefinition.schemas";

export const getBookingsResponseMock = (
  overrideResponse: Partial<ApiResponsePagedResponseDTOBookingResponseDTO> = {}
): ApiResponsePagedResponseDTOBookingResponseDTO => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  code: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  message: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  data: faker.helpers.arrayElement([
    {
      content: faker.helpers.arrayElement([
        Array.from(
          { length: faker.number.int({ min: 1, max: 10 }) },
          (_, i) => i + 1
        ).map(() => ({
          id: faker.helpers.arrayElement([
            faker.number.int({ min: undefined, max: undefined }),
            undefined,
          ]),
          reference: faker.helpers.arrayElement([
            faker.string.alpha(20),
            undefined,
          ]),
          status: faker.helpers.arrayElement([
            faker.string.alpha(20),
            undefined,
          ]),
          userId: faker.helpers.arrayElement([
            faker.number.int({ min: undefined, max: undefined }),
            undefined,
          ]),
          flightId: faker.helpers.arrayElement([
            faker.number.int({ min: undefined, max: undefined }),
            undefined,
          ]),
          bookingTime: faker.helpers.arrayElement([
            `${faker.date.past().toISOString().split(".")[0]}Z`,
            undefined,
          ]),
          totalPrice: faker.helpers.arrayElement([
            faker.number.int({ min: undefined, max: undefined }),
            undefined,
          ]),
          passengers: faker.helpers.arrayElement([
            Array.from(
              { length: faker.number.int({ min: 1, max: 10 }) },
              (_, i) => i + 1
            ).map(() => ({
              firstName: faker.string.alpha(20),
              lastName: faker.string.alpha(20),
              email: faker.string.alpha(20),
            })),
            undefined,
          ]),
        })),
        undefined,
      ]),
      pageNumber: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      pageSize: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      totalElements: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      totalPages: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      first: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
      last: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
    },
    undefined,
  ]),
  ...overrideResponse,
});

export const getCreateBookingResponseMock = (
  overrideResponse: Partial<ApiResponseBookingResponseDTO> = {}
): ApiResponseBookingResponseDTO => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  code: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  message: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  data: faker.helpers.arrayElement([
    {
      id: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      reference: faker.helpers.arrayElement([
        faker.string.alpha(20),
        undefined,
      ]),
      status: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      userId: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      flightId: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      bookingTime: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split(".")[0]}Z`,
        undefined,
      ]),
      totalPrice: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      passengers: faker.helpers.arrayElement([
        Array.from(
          { length: faker.number.int({ min: 1, max: 10 }) },
          (_, i) => i + 1
        ).map(() => ({
          firstName: faker.string.alpha(20),
          lastName: faker.string.alpha(20),
          email: faker.string.alpha(20),
        })),
        undefined,
      ]),
    },
    undefined,
  ]),
  ...overrideResponse,
});

export const getBookingDetailResponseMock = (
  overrideResponse: Partial<ApiResponseBookingResponseDTO> = {}
): ApiResponseBookingResponseDTO => ({
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  code: faker.helpers.arrayElement([
    faker.number.int({ min: undefined, max: undefined }),
    undefined,
  ]),
  message: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
  data: faker.helpers.arrayElement([
    {
      id: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      reference: faker.helpers.arrayElement([
        faker.string.alpha(20),
        undefined,
      ]),
      status: faker.helpers.arrayElement([faker.string.alpha(20), undefined]),
      userId: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      flightId: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      bookingTime: faker.helpers.arrayElement([
        `${faker.date.past().toISOString().split(".")[0]}Z`,
        undefined,
      ]),
      totalPrice: faker.helpers.arrayElement([
        faker.number.int({ min: undefined, max: undefined }),
        undefined,
      ]),
      passengers: faker.helpers.arrayElement([
        Array.from(
          { length: faker.number.int({ min: 1, max: 10 }) },
          (_, i) => i + 1
        ).map(() => ({
          firstName: faker.string.alpha(20),
          lastName: faker.string.alpha(20),
          email: faker.string.alpha(20),
        })),
        undefined,
      ]),
    },
    undefined,
  ]),
  ...overrideResponse,
});

export const getBookingsMockHandler = (
  overrideResponse?:
    | ApiResponsePagedResponseDTOBookingResponseDTO
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0]
      ) =>
        | Promise<ApiResponsePagedResponseDTOBookingResponseDTO>
        | ApiResponsePagedResponseDTOBookingResponseDTO)
) => {
  return http.get("*/api/bookings", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getBookingsResponseMock()
      ),
      { status: 200, headers: { "Content-Type": "application/json" } }
    );
  });
};

export const getCreateBookingMockHandler = (
  overrideResponse?:
    | ApiResponseBookingResponseDTO
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0]
      ) =>
        | Promise<ApiResponseBookingResponseDTO>
        | ApiResponseBookingResponseDTO)
) => {
  return http.post("*/api/bookings", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getCreateBookingResponseMock()
      ),
      { status: 200, headers: { "Content-Type": "application/json" } }
    );
  });
};

export const getBookingDetailMockHandler = (
  overrideResponse?:
    | ApiResponseBookingResponseDTO
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0]
      ) =>
        | Promise<ApiResponseBookingResponseDTO>
        | ApiResponseBookingResponseDTO)
) => {
  return http.get("*/api/bookings/:id", async (info) => {
    await delay(1000);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getBookingDetailResponseMock()
      ),
      { status: 200, headers: { "Content-Type": "application/json" } }
    );
  });
};
export const getBookingControllerMock = () => [
  getBookingsMockHandler(),
  getCreateBookingMockHandler(),
  getBookingDetailMockHandler(),
];
