/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ApiResponseBookingResponseDTO,
  ApiResponsePagedResponseDTOBookingResponseDTO,
  BookingRequestDTO,
  GetBookingsParams,
} from "../openAPIDefinition.schemas";

import { axiosInstance } from ".././axiosInstance";

export const getBookings = (
  params?: GetBookingsParams,
  signal?: AbortSignal
) => {
  return axiosInstance<ApiResponsePagedResponseDTOBookingResponseDTO>({
    url: `/api/bookings`,
    method: "GET",
    params,
    signal,
  });
};

export const getBookingsQueryKey = (params?: GetBookingsParams) => {
  return [`/api/bookings`, ...(params ? [params] : [])] as const;
};

export const getBookingsQueryOptions = <
  TData = Awaited<ReturnType<typeof getBookings>>,
  TError = unknown
>(
  params?: GetBookingsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBookings>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getBookingsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getBookings>>> = ({
    signal,
  }) => getBookings(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getBookings>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetBookingsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getBookings>>
>;
export type GetBookingsQueryError = unknown;

export function useGetBookings<
  TData = Awaited<ReturnType<typeof getBookings>>,
  TError = unknown
>(
  params: undefined | GetBookingsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBookings>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBookings>>,
          TError,
          Awaited<ReturnType<typeof getBookings>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBookings<
  TData = Awaited<ReturnType<typeof getBookings>>,
  TError = unknown
>(
  params?: GetBookingsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBookings>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBookings>>,
          TError,
          Awaited<ReturnType<typeof getBookings>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBookings<
  TData = Awaited<ReturnType<typeof getBookings>>,
  TError = unknown
>(
  params?: GetBookingsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBookings>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetBookings<
  TData = Awaited<ReturnType<typeof getBookings>>,
  TError = unknown
>(
  params?: GetBookingsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBookings>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getBookingsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const createBooking = (
  bookingRequestDTO: BookingRequestDTO,
  signal?: AbortSignal
) => {
  return axiosInstance<ApiResponseBookingResponseDTO>({
    url: `/api/bookings`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: bookingRequestDTO,
    signal,
  });
};

export const getCreateBookingMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createBooking>>,
    TError,
    { data: BookingRequestDTO },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createBooking>>,
  TError,
  { data: BookingRequestDTO },
  TContext
> => {
  const mutationKey = ["createBooking"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createBooking>>,
    { data: BookingRequestDTO }
  > = (props) => {
    const { data } = props ?? {};

    return createBooking(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateBookingMutationResult = NonNullable<
  Awaited<ReturnType<typeof createBooking>>
>;
export type CreateBookingMutationBody = BookingRequestDTO;
export type CreateBookingMutationError = unknown;

export const useCreateBooking = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createBooking>>,
      TError,
      { data: BookingRequestDTO },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createBooking>>,
  TError,
  { data: BookingRequestDTO },
  TContext
> => {
  const mutationOptions = getCreateBookingMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getBookingDetail = (id: number, signal?: AbortSignal) => {
  return axiosInstance<ApiResponseBookingResponseDTO>({
    url: `/api/bookings/${id}`,
    method: "GET",
    signal,
  });
};

export const getBookingDetailQueryKey = (id: number) => {
  return [`/api/bookings/${id}`] as const;
};

export const getBookingDetailQueryOptions = <
  TData = Awaited<ReturnType<typeof getBookingDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBookingDetail>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getBookingDetailQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getBookingDetail>>
  > = ({ signal }) => getBookingDetail(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getBookingDetail>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetBookingDetailQueryResult = NonNullable<
  Awaited<ReturnType<typeof getBookingDetail>>
>;
export type GetBookingDetailQueryError = unknown;

export function useGetBookingDetail<
  TData = Awaited<ReturnType<typeof getBookingDetail>>,
  TError = unknown
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBookingDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBookingDetail>>,
          TError,
          Awaited<ReturnType<typeof getBookingDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBookingDetail<
  TData = Awaited<ReturnType<typeof getBookingDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBookingDetail>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBookingDetail>>,
          TError,
          Awaited<ReturnType<typeof getBookingDetail>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBookingDetail<
  TData = Awaited<ReturnType<typeof getBookingDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBookingDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetBookingDetail<
  TData = Awaited<ReturnType<typeof getBookingDetail>>,
  TError = unknown
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBookingDetail>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getBookingDetailQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
