/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';

import type {
  ApiResponseAuthResponseDTO,
  ApiResponseBoolean,
  ApiResponseVoid
} from '../openAPIDefinition.schemas';


export const getRegisterResponseMock = (overrideResponse: Partial< ApiResponseAuthResponseDTO > = {}): ApiResponseAuthResponseDTO => ({success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), code: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), message: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), data: faker.helpers.arrayElement([{accessToken: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), refreshToken: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), accessTokenExpiresIn: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), userInfo: faker.helpers.arrayElement([{id: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), email: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), firstName: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), lastName: faker.helpers.arrayElement([faker.string.alpha(20), undefined])}, undefined])}, undefined]), ...overrideResponse})

export const getRefreshTokenResponseMock = (overrideResponse: Partial< ApiResponseAuthResponseDTO > = {}): ApiResponseAuthResponseDTO => ({success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), code: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), message: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), data: faker.helpers.arrayElement([{accessToken: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), refreshToken: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), accessTokenExpiresIn: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), userInfo: faker.helpers.arrayElement([{id: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), email: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), firstName: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), lastName: faker.helpers.arrayElement([faker.string.alpha(20), undefined])}, undefined])}, undefined]), ...overrideResponse})

export const getLogoutResponseMock = (overrideResponse: Partial< ApiResponseVoid > = {}): ApiResponseVoid => ({success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), code: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), message: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), data: faker.helpers.arrayElement([{}, undefined]), ...overrideResponse})

export const getLoginResponseMock = (overrideResponse: Partial< ApiResponseAuthResponseDTO > = {}): ApiResponseAuthResponseDTO => ({success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), code: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), message: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), data: faker.helpers.arrayElement([{accessToken: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), refreshToken: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), accessTokenExpiresIn: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), userInfo: faker.helpers.arrayElement([{id: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), email: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), firstName: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), lastName: faker.helpers.arrayElement([faker.string.alpha(20), undefined])}, undefined])}, undefined]), ...overrideResponse})

export const getCheckResponseMock = (overrideResponse: Partial< ApiResponseBoolean > = {}): ApiResponseBoolean => ({success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), code: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), message: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), data: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), ...overrideResponse})


export const getRegisterMockHandler = (overrideResponse?: ApiResponseAuthResponseDTO | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ApiResponseAuthResponseDTO> | ApiResponseAuthResponseDTO)) => {
  return http.post('*/api/auth/register', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getRegisterResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getRefreshTokenMockHandler = (overrideResponse?: ApiResponseAuthResponseDTO | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ApiResponseAuthResponseDTO> | ApiResponseAuthResponseDTO)) => {
  return http.post('*/api/auth/refresh', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getRefreshTokenResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getLogoutMockHandler = (overrideResponse?: ApiResponseVoid | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ApiResponseVoid> | ApiResponseVoid)) => {
  return http.post('*/api/auth/logout', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getLogoutResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getLoginMockHandler = (overrideResponse?: ApiResponseAuthResponseDTO | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ApiResponseAuthResponseDTO> | ApiResponseAuthResponseDTO)) => {
  return http.post('*/api/auth/login', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getLoginResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getCheckMockHandler = (overrideResponse?: ApiResponseBoolean | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ApiResponseBoolean> | ApiResponseBoolean)) => {
  return http.get('*/api/auth/check', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getCheckResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}
export const getAuthControllerMock = () => [
  getRegisterMockHandler(),
  getRefreshTokenMockHandler(),
  getLogoutMockHandler(),
  getLoginMockHandler(),
  getCheckMockHandler()
]
